#!/bin/bash

set -o nounset
set -o errexit
set -o noglob
set -o pipefail

app="--app ${TOOLS_APP}"

main() {
    getCBKey && {
        echo "The Coinbase API key is already configured (see above)."
        return 0
    }

    cat <<EOF
Setup your Coinbase API key by running:

    heroku config:set $app COINBASE_API_KEY=<your-key>

EOF
}

getCBKey() {
    cfg="$(heroku config $app)"
    grep COINBASE_API_KEY <<<"${cfg}"
}

die() {
    printf 'Error: %s\n' "$1"
    exit 1
}

main "$@"
